// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmdPZU2wwgqVKFgkudu5BnMkqb9-i2vpw',
    appId: '1:1093831602906:web:7b78c1b86ae8eac0a56be3',
    messagingSenderId: '1093831602906',
    projectId: 'tailorconnectapp',
    authDomain: 'tailorconnectapp.firebaseapp.com',
    databaseURL: 'https://tailorconnectapp-default-rtdb.firebaseio.com',
    storageBucket: 'tailorconnectapp.appspot.com',
    measurementId: 'G-RZT1RGH73K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtUgwEBVhLmodnnPWyHyEo7-qhZAEcTFs',
    appId: '1:1093831602906:android:51133de4e97a368aa56be3',
    messagingSenderId: '1093831602906',
    projectId: 'tailorconnectapp',
    databaseURL: 'https://tailorconnectapp-default-rtdb.firebaseio.com',
    storageBucket: 'tailorconnectapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Wef_SlkKgdm8ARFUy0wlmAAb6V8j3iQ',
    appId: '1:1093831602906:ios:19302867f676ac06a56be3',
    messagingSenderId: '1093831602906',
    projectId: 'tailorconnectapp',
    databaseURL: 'https://tailorconnectapp-default-rtdb.firebaseio.com',
    storageBucket: 'tailorconnectapp.appspot.com',
    iosBundleId: 'com.example.tailorsConnect',
  );
}
